name = "Microcontroller Starter"

description = "A starter template for working with microcontrollers (based on the app-template project by knurling https://github.com/knurling-rs/app-template)"

kickstart_version = 1

ignore = [
       "README.md"
]

[[variables]]
name = "project_name"
default = "example"
prompt = "What is the name for your project?"
validation = "^([a-zA-Z][a-zA-Z0-9_-]+)$"

[[variables]]
name = "microcontroller"
default = "nrf52840"
prompt = "What microcontroller is the project targeting?"
choices = [
        "nrf52840"
]